<a href="https://colab.research.google.com/github/aannddrree/turmauniaraIA2/blob/main/AprendizadoDeMaquinaAvancado.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **1. Modelos Generativos**

GANs (Redes Gerativas Adversariais)
Um exemplo simples de GAN para gerar imagens de dígitos escritos à mão (usando o dataset MNIST):

In [8]:
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers, Sequential

def build_generator():
    model = Sequential([
        layers.Dense(16, activation='relu', input_dim=1),
        layers.Dense(1)
    ])
    return model

def build_discriminator():
    model = Sequential([
        layers.Dense(16, activation='relu', input_dim=1),
        layers.Dense(1, activation='sigmoid')
    ])
    return model

generator = build_generator()
discriminator = build_discriminator()
discriminator.compile(optimizer='adam', loss='binary_crossentropy')

# Conectando o gerador ao discriminador
discriminator.trainable = False
gan = Sequential([generator, discriminator])
gan.compile(optimizer='adam', loss='binary_crossentropy')

real_data = np.array([[6.0], [7.0], [8.0]])
labels_real = np.ones((3, 1))  # Rótulos para dados reais (1)
labels_fake = np.zeros((3, 1)) # Rótulos para dados falsos (0)

epochs = 1000
batch_size = 3

for epoch in range(epochs):
    # Gerando dados falsos (números)
    noise = np.random.normal(0, 1, (batch_size, 1))
    generated_data = generator.predict(noise)

    # Treinando o discriminador com dados reais e falsos
    d_loss_real = discriminator.train_on_batch(real_data, labels_real)
    d_loss_fake = discriminator.train_on_batch(generated_data, labels_fake)

    # Treinando o gerador (enganar o discriminador)
    noise = np.random.normal(0, 1, (batch_size, 1))
    gan_loss = gan.train_on_batch(noise, labels_real)

    if epoch % 100 == 0:
        print(f"Epoch {epoch}, Loss D Real: {d_loss_real}, Loss D Fake: {d_loss_fake}, Loss G: {gan_loss}")


noise = np.random.normal(0, 1, (5, 1))
generated_numbers = generator.predict(noise)
print("Números gerados:", generated_numbers)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
Epoch 0, Loss D Real: 0.6009543538093567, Loss D Fake: 0.6464653611183167, Loss G: [array(0.64646536, dtype=float32), array(0.64646536, dtype=float32)]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
1/1 ━━━━━━━━

## **2. Aprendizado por Reforço**
Q-Learning
Um exemplo simples de Q-learning para resolver o problema do "Frozen Lake" no OpenAI Gym:

In [3]:
import numpy as np
import gym

env = gym.make('FrozenLake-v1')

# Inicializando a tabela Q
Q = np.zeros([env.observation_space.n, env.action_space.n])

# Parâmetros
learning_rate = 0.8
gamma = 0.95
episodes = 1000

# Treinamento
for episode in range(episodes):
    state = env.reset()
    done = False
    while not done:
        action = np.argmax(Q[state] + np.random.randn(1, env.action_space.n) * (1. / (episode + 1)))
        next_state, reward, done, _ = env.step(action)
        Q[state, action] = Q[state, action] + learning_rate * (reward + gamma * np.max(Q[next_state]) - Q[state, action])
        state = next_state

print("Q-Table após treinamento:")
print(Q)


/usr/local/lib/python3.10/dist-packages/gym/core.py:317: DeprecationWarning: WARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
/usr/local/lib/python3.10/dist-packages/gym/wrappers/step_api_compatibility.py:39: DeprecationWarning: WARN: Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
/usr/local/lib/python3.10/dist-packages/gym/utils/passive_env_checker.py:241: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):


Q-Table após treinamento:
[[1.42359244e-01 3.07473476e-03 3.10796328e-03 3.28680615e-03]
 [7.63773141e-04 2.03251217e-03 5.58380051e-04 5.53668540e-02]
 [9.30343114e-02 2.26375396e-03 2.04999426e-03 2.18845367e-03]
 [1.81035235e-03 4.34417818e-04 4.25102524e-04 2.22709319e-03]
 [1.90140761e-01 1.16787101e-04 1.50556983e-04 5.64774742e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [4.85495170e-04 1.46311785e-07 1.93004324e-02 7.31656641e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [9.87818076e-05 7.07506051e-04 4.97882308e-04 2.30027462e-01]
 [7.69972266e-04 3.67138925e-01 8.48263312e-04 4.55938478e-04]
 [2.41345097e-01 1.20956785e-03 1.54731553e-05 1.39139807e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 6.55790661e-03 7.35107844e-01 8.71578086e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 9.53011078e-01]
 [0.00000000e+00 0.00000000e+

## **3. Algoritmos de Otimização e Busca**
Gradiente Descendente Simples
Um exemplo básico de gradiente descendente para encontrar o mínimo de uma função quadrática:

In [4]:
# Função de custo: f(x) = x^2
def cost_function(x):
    return x**2

# Derivada: f'(x) = 2x
def gradient(x):
    return 2*x

# Gradiente descendente
x = 10  # Ponto de partida
learning_rate = 0.1
epochs = 100

for i in range(epochs):
    x -= learning_rate * gradient(x)

print(f"Valor mínimo encontrado: {x}")


Valor mínimo encontrado: 2.0370359763344878e-09


## **4. Hiperparametrização e Tuning de Modelos**
Grid Search para Hiperparâmetros
Um exemplo de Grid Search utilizando o scikit-learn para ajustar hiperparâmetros de um modelo SVM:

In [5]:
from sklearn import datasets
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC

# Carregar dataset
iris = datasets.load_iris()
X, y = iris.data, iris.target

# Definir o modelo
svc = SVC()

# Definir os hiperparâmetros para busca
param_grid = {'C': [0.1, 1, 10, 100], 'kernel': ['linear', 'rbf']}

# Grid Search
grid_search = GridSearchCV(svc, param_grid, cv=5)
grid_search.fit(X, y)

print("Melhores hiperparâmetros:", grid_search.best_params_)
print("Melhor precisão:", grid_search.best_score_)


Melhores hiperparâmetros: {'C': 1, 'kernel': 'linear'}
Melhor precisão: 0.9800000000000001
